# Build stage
FROM golang:1.24.4-alpine AS builder

WORKDIR /app

COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/api ./cmd/api/main.go
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/task ./cmd/cli/main.go

# Final stage
FROM alpine:latest

WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/api /app/api
COPY --from=builder /app/task /app/task
COPY environments /app/environments

EXPOSE 4000
CMD ["./api"]