version: "3.8"

services:
  api:
    build: .
    image: go-fiber-api
    container_name: go-fiber-api
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - go-fiber-api:/go
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-05-07T06-41-25Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command:
      ["server", "/data", "--address", ":9000", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    restart: always

  createbuckets:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/go-fiber-dev;
      /usr/bin/mc policy set download myminio/go-fiber-dev;
      /usr/bin/mc anonymous set download myminio/go-fiber-dev

      /usr/bin/mc mb myminio/go-fiber-public-dev;
      /usr/bin/mc policy set download myminio/go-fiber-public-dev;
      /usr/bin/mc anonymous set download myminio/go-fiber-public-dev;

      exit 0;
      "
    depends_on:
      - minio

volumes:
  go-fiber-api:
    name: go-fiber-api
  postgres:
    name: postgres
  redis:
    name: redis
  redisinsight:
    name: redisinsight
  pgadmin:
    name: pgadmin
  minio:
    name: minio

networks:
  default:
    name: go-fiber-network
