// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewEmailRepository creates a new instance of EmailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailRepository {
	mock := &EmailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailRepository is an autogenerated mock type for the EmailRepository type
type EmailRepository struct {
	mock.Mock
}

type EmailRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailRepository) EXPECT() *EmailRepository_Expecter {
	return &EmailRepository_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type EmailRepository
func (_mock *EmailRepository) SendEmail(to string, subject string, templateName string, data interface{}) error {
	ret := _mock.Called(to, subject, templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, interface{}) error); ok {
		r0 = returnFunc(to, subject, templateName, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailRepository_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type EmailRepository_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - to string
//   - subject string
//   - templateName string
//   - data interface{}
func (_e *EmailRepository_Expecter) SendEmail(to interface{}, subject interface{}, templateName interface{}, data interface{}) *EmailRepository_SendEmail_Call {
	return &EmailRepository_SendEmail_Call{Call: _e.mock.On("SendEmail", to, subject, templateName, data)}
}

func (_c *EmailRepository_SendEmail_Call) Run(run func(to string, subject string, templateName string, data interface{})) *EmailRepository_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmailRepository_SendEmail_Call) Return(err error) *EmailRepository_SendEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailRepository_SendEmail_Call) RunAndReturn(run func(to string, subject string, templateName string, data interface{}) error) *EmailRepository_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}
